@startuml space



class Alien
Class Pulpo
Class Calamar
Class 
class Cañon
class Barrera
class proyectil
Class Vida 
Class juego 
Class puntuacion 
Class Nivel
Class jugador

Juego "1"*--"*"Nivel
Nivel *-- Alien
Nivel -- Barrera
Nivel -- Cañon


Jugador o-- Cañon
Jugador *-- Vida
Jugador *-- puntuacion
Cañon o-- proyectil
Juego *-- Jugador
Proyectil o-- Colesionable
Barrrera --|> colesionable
Alien  --|> colesionable

Pulpo --|> Alien
Calamar--|> Alien
Cangrejo--|> Alien
@enduml